
services:
    nginx:
        container_name: ${PROJECT_NAME:-boilerplate}_nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ..:/var/www
        depends_on:
            - php
        networks:
            - backend

    php:
        container_name: ${PROJECT_NAME:-boilerplate}_php
        build:
            context: ..
            dockerfile: .docker/Dockerfile
        volumes:
            - ..:/var/www
        networks:
            - backend
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:8.0
        container_name: ${PROJECT_NAME:-boilerplate}_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-boilerplate_db}
           # MYSQL_USER: ${MYSQL_USER:-root}
          #  MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
        volumes:
            - boilerplate_db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - backend
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            timeout: 5s
            retries: 5

    phpmyadmin:
            image: phpmyadmin:latest
            container_name: ${PROJECT_NAME:-boilerplate}_phpmyadmin
            restart: always
            depends_on:
                - mysql
            environment:
                PMA_HOST: mysql
                PMA_PORT: 3306
            ports:
                - "8083:80"
            networks:
                - backend

volumes:
    boilerplate_db_data:

networks:
    backend:
