services:
    grafana:
        image: grafana/grafana
        container_name: ${PROJECT_NAME:-boilerplate}_grafana
        restart: unless-stopped
        ports:
            - '3000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
            - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
        networks:
            - monitoring

    promtail:
        image: grafana/promtail:3.6.0
        container_name: ${PROJECT_NAME:-boilerplate}_promtail
        restart: unless-stopped
        volumes:
            - ../../var/log:/var/log/boilerplate-symfony:ro
            - ./promtail-config.yaml:/etc/promtail/config.yaml:ro
            - ./promtail-data:/var/lib/promtail
        depends_on:
            - loki
        command: -config.file=/etc/promtail/config.yaml
        networks:
            - monitoring
        labels:
            - "traefik.enable=false"

    loki:
        image: grafana/loki:2.8.2
        container_name: ${PROJECT_NAME:-boilerplate}_loki
        restart: unless-stopped
        ports:
            - '3100:3100'
            - '9096:9096'
        volumes:
            - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
        command: -config.file=/etc/loki/loki-config.yaml
        networks:
            - monitoring

volumes:
    grafana-storage: {}
    promtail-data: {}

networks:
    monitoring:
        driver: bridge
