server:
    http_listen_port: 9080
    grpc_listen_port: 0
positions:
    filename: /var/lib/promtail/positions.yaml
clients:
    - url: http://boilerplate-loki:3100/loki/api/v1/push
scrape_configs:
    - job_name: boilerplate-symfony
#      decompression:
#          enabled: true
#          initial_delay: 10s
#          format: gz
      static_configs:
          - targets:
                - localhost
            labels:
                job: boilerplate-symfony
                __path__: /var/log/boilerplate-symfony/**/*.log
